version: '3.6'

services:
  flask-api:
    build: ./flask-api/
    depends_on:
      - db
    environment: 
      STAGE: staging
      SQLALCHEMY_DATABASE_URI: postgresql://${db_user}:${db_password}@${db_host}:${db_port}/${db_name}
    networks:
      - default
    ports:
      - 5000:5000
    volumes:
      - ./flask-api:/usr/src/app/app
      - ./migrations:/usr/src/app/migrations
    restart: always
    env_file:
      - ./flask-api/.env

  db:
    environment:
      db_user: ${db_user}
      db_password: ${db_password}
      db_host: ${db_host}
      db_name: ${db_name}
      db_port: ${db_port}
      test_db_name: ${test_db_name}
    image: postgres:11
    networks:
      - default
    ports: 
      - 5434:5434
    restart: always
    volumes: 
      - ./postgres-data:/var/lib/postgresql/data 